server:
  port: 8888


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vik2982/spring-boot.git
          searchPaths: spring-cloud-config-repo
          default-label: master